### PR TITLE
Checkout process

### PR DESCRIPTION
**Pull request by baraabd**

### CODE REVIEW

**Review by Moraxan — CHANGES_REQUESTED** [review]
Tests are running in headed mode. Please add headless

        options.addArguments("--headless");
 
Other than that well done. Also good not to have clashes and duplicate steps between the two stepfiles.

**Comment by trumanders** [comment]
I think we need some more  options, but I am not sure. When I managed to make the pipeline run selenium tests, I added these options to ChromeOptions:

   options.addArguments("--remote-allow-origins=*");
        options.addArguments("--headless");
        options.addArguments("incognito");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        
   But --headless should at least be added to make github actions run tests. (And it's less annoying when running locally)

**Comment by baraabd** [comment]
Added headless

**Review by Moraxan — APPROVED** [review]
Looks good

**Pull request merged**
